import logging
from typing import List
from .base import ImageProvider

# Импортируем все провайдеры
from .playground import PlaygroundProvider  # Переименовали класс? Если нет, оставь HuggingFaceProvider
from .flux_klein import FluxKleinProvider
from .qwen import QwenProvider
from .z_image import ZImageProvider
from .radames import RadamesProvider
from .pixazo import PixazoProvider
from .leonardo import LeonardoProvider

# Настраиваем логгер для этого файла
logger = logging.getLogger(__name__)

# Приглушаем httpx логи (heartbeat 404 и прочий шум от Gradio Client)
logging.getLogger("httpx").setLevel(logging.WARNING)


def generate_image_sync(
        prompt: str,
        negative_prompt: str,
        width: int,
        height: int
) -> bytes:

    # === СТРАТЕГИЯ ===
    # 1. Сначала пробуем самые крутые бесплатные (Playground, Flux, Qwen)
    # 2. Потом пробуем быстрые/CPU (Radames Lightning)
    # 3. LeonardoAI (универсальный)
    # 4. В самом конце - платный/стабильный (Pixazo)

    providers: List[ImageProvider] = [
        #PlaygroundProvider(),  # 1. Топ качество (45 сек)
        #FluxKleinProvider(),  # 2. Быстрый и крутой (30 сек)
        LeonardoProvider(),    # 3. Leonardo AI (GPT-1.5 / Nano / SeeDream)
        #QwenProvider(),  # 4. Умный, понимает сцены (60 сек)
        #ZImageProvider(),  # 5. Тяжелый, но качественный (45 сек)
        #RadamesProvider(),  # 6. Спидстер SDXL Lightning (15 сек)
        #PixazoProvider()  # 7. ПОСЛЕДНИЙ РУБЕЖ (Всегда работает)
    ]

    errors = []

    # Логируем начало всей операции
    logger.info(f"🎬 [Orchestrator] New Request: '{prompt[:40]}...' Size: {width}x{height}")

    for i, provider in enumerate(providers, 1):
        logger.info(f"🔄 [Orchestrator] Step {i}/{len(providers)}: Launching >>> {provider.name} <<<")

        try:
            # Запускаем генерацию
            result = provider.generate(prompt, negative_prompt, width, height)

            # Если дошли сюда - значит успех
            logger.info(f"✅ [Orchestrator] SUCCESS! Image generated by {provider.name}")
            return result

        except Exception as e:
            err_msg = str(e)

            # Красиво логируем ошибку
            if "quota" in err_msg.lower() or "429" in err_msg:
                logger.warning(f"[Orchestrator] {provider.name} hit QUOTA/LIMIT. Moving next...")
            elif "timeout" in err_msg.lower():
                logger.warning(f"[Orchestrator] {provider.name} TIMED OUT (Queue too long). Moving next...")
            else:
                logger.error(f"[Orchestrator] {provider.name} FAILED: {err_msg}")

            # Сохраняем ошибку для финального отчета
            errors.append(f"{provider.name}: {err_msg}")
            continue

    # Если цикл закончился, а мы здесь — значит упал даже Pixazo
    final_error = f"ALL PROVIDERS DEAD. Details: {'; '.join(errors)}"
    logger.critical(final_error)
    raise Exception(final_error)