import logging
import time
from typing import List, Dict, Type
from .base import ImageProvider

# Импортируем все провайдеры
from .playground import PlaygroundProvider
from .flux_klein import FluxKleinProvider
from .qwen import QwenProvider
from .z_image_kieai import ZImageKieAIProvider
from .radames import RadamesProvider
from .pixazo import PixazoProvider
from .leonardo import LeonardoProvider

logger = logging.getLogger(__name__)

logging.getLogger("httpx").setLevel(logging.WARNING)

# Провайдеры, которые никогда не банятся (всегда в ротации)
NEVER_BLACKLIST: set[Type[ImageProvider]] = {PixazoProvider}

# Blacklist: класс провайдера -> timestamp когда упал
# Провайдер исключается на 24 часа после первой ошибки
_blacklist: Dict[Type[ImageProvider], float] = {}
_BLACKLIST_TTL = 24 * 60 * 60  # секунд


def _is_blacklisted(cls: Type[ImageProvider]) -> bool:
    if cls in NEVER_BLACKLIST:
        return False
    banned_at = _blacklist.get(cls)
    if banned_at is None:
        return False
    if time.time() - banned_at >= _BLACKLIST_TTL:
        del _blacklist[cls]
        logger.info(f"🔓 [Orchestrator] {cls.__name__} unbanned after 24h cooldown")
        return False
    return True


def _ban(cls: Type[ImageProvider]) -> None:
    if cls in NEVER_BLACKLIST:
        return
    _blacklist[cls] = time.time()
    logger.warning(f"🚫 [Orchestrator] {cls.__name__} banned for {_BLACKLIST_TTL // 3600}h")


def generate_image_sync(
        prompt: str,
        negative_prompt: str,
        width: int,
        height: int
) -> bytes:

    # === СТРАТЕГИЯ ===
    # 1. Сначала пробуем самые крутые бесплатные (Playground, Flux, Qwen)
    # 2. Потом пробуем быстрые/CPU (Radames Lightning)
    # 3. LeonardoAI (универсальный)
    # 4. В самом конце - платный/стабильный (Pixazo) — никогда не банится

    all_providers: List[Type[ImageProvider]] = [
        PlaygroundProvider,    # 1. Топ качество (45 сек)
        FluxKleinProvider,     # 2. Быстрый и крутой (30 сек)
        LeonardoProvider,      # 3. Leonardo AI (GPT-1.5 / Nano / SeeDream)
        # QwenProvider,        # 4. Умный, понимает сцены (60 сек)
        ZImageKieAIProvider,   # 5. Z-Image via kie.ai (120 сек таймаут)
        # RadamesProvider,     # 6. Спидстер SDXL Lightning (15 сек)
        PixazoProvider,        # 7. ПОСЛЕДНИЙ РУБЕЖ (Всегда работает, не банится)
    ]

    active = [cls for cls in all_providers if not _is_blacklisted(cls)]

    skipped = len(all_providers) - len(active)
    logger.info(f"🎬 [Orchestrator] New Request: '{prompt[:40]}...' Size: {width}x{height} "
                f"| Active: {len(active)}/{len(all_providers)} providers"
                + (f" ({skipped} blacklisted)" if skipped else ""))

    errors = []

    for i, cls in enumerate(active, 1):
        provider = cls()
        logger.info(f"🔄 [Orchestrator] Step {i}/{len(active)}: Launching >>> {provider.name} <<<")

        try:
            result = provider.generate(prompt, negative_prompt, width, height)
            logger.info(f"✅ [Orchestrator] SUCCESS! Image generated by {provider.name}")
            return result

        except Exception as e:
            err_msg = str(e)

            if "quota" in err_msg.lower() or "429" in err_msg:
                logger.warning(f"[Orchestrator] {provider.name} hit QUOTA/LIMIT. Moving next...")
            elif "timeout" in err_msg.lower():
                logger.warning(f"[Orchestrator] {provider.name} TIMED OUT. Moving next...")
            else:
                logger.error(f"[Orchestrator] {provider.name} FAILED: {err_msg}")

            _ban(cls)
            errors.append(f"{provider.name}: {err_msg}")

    final_error = f"ALL PROVIDERS DEAD. Details: {'; '.join(errors)}"
    logger.critical(final_error)
    raise Exception(final_error)
